name: Mobile

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
          flutter-version: "1.21.0-9.2.pre"

      - run: flutter pub get

      - run: flutter build apk --dart-define=SERVER_URL='${{ secrets.SERVER_URL }}'
      - uses: actions/upload-artifact@v2
        with:
          name: Android app
          path: client/build/app/outputs/flutter-apk/app-release.apk

      - run: flutter build ios --release --no-codesign --dart-define=SERVER_URL='${{ secrets.SERVER_URL }}'
      - uses: actions/upload-artifact@v2
        with:
          name: iOS app
          path: client/build/ios/iphoneos/Runner.app
