name: Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: beta

      - run: flutter channel beta
      - run: flutter upgrade
      - run: flutter config --enable-web
      - run: flutter pub get
        working-directory: client
      - run: yarn install
        working-directory: server
      - run: yarn build:prod
        working-directory: server

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: server/dist

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: server/dist

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: archanes/smart-strike:latest
